"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@material-tailwind/react";
import TopNavbar from '../components/compound/TopNavbar';
import BottomNavbar from '@/components/compound/BottomNavbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
       
        <body className={inter.className}>
          <TopNavbar />
          <BottomNavbar />
            {children}
        </body>
      </html>
    </ThemeProvider>
  )
}
